const sendBtn = document.getElementById('send-btn');
const userInput = document.getElementById('user-input');
const chatWindow = document.getElementById('chat-window');
const welcomeScreen = document.getElementById('welcome-screen');
const voiceBtn = document.getElementById('voice-btn');

// --- SIDEBAR ---
document.getElementById('open-sidebar').onclick = () => document.getElementById('sidebar').classList.add('open');
document.getElementById('close-sidebar').onclick = () => document.getElementById('sidebar').classList.remove('open');

// --- VOICE ---
const recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
voiceBtn.onclick = () => { recognition.start(); voiceBtn.classList.add('active'); };
recognition.onresult = (e) => { 
    userInput.value = e.results[0][0].transcript; 
    voiceBtn.classList.remove('active'); 
    sendBtn.click(); 
};
function speak(text) {
    const u = new SpeechSynthesisUtterance(text);
    u.pitch = 1.1;
    window.speechSynthesis.speak(u);
}

// --- MAIN AI LOGIC ---
sendBtn.onclick = async () => {
    const text = userInput.value;
    if (!text.trim()) return;

    welcomeScreen.style.display = 'none';
    chatWindow.style.display = 'flex';
    renderMessage(text, 'user');
    userInput.value = "";

    // GLOWING SEARCHING STATE
    const thinkingDiv = document.createElement('div');
    thinkingDiv.className = 'searching-bubble';
    thinkingDiv.innerText = "Lyromi is searching current data...";
    chatWindow.appendChild(thinkingDiv);
    chatWindow.scrollTop = chatWindow.scrollHeight;

    try {
        // IMAGE GEN CHECK
        if (text.toLowerCase().includes("image") || text.toLowerCase().includes("picture")) {
            const prompt = text.replace(/image|picture|show me/gi, "").trim();
            const imgUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&nologo=true`;
            setTimeout(() => {
                thinkingDiv.classList.remove('searching-bubble');
                thinkingDiv.innerHTML = `<div class="bubble">Generated by Lyromi:<br><img src="${imgUrl}"></div>`;
                speak("I have generated that image for you.");
            }, 3000);
            return;
        }

        // CHAT CALL
        const res = await fetch('/api/chat', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ message: text })
        });
        const data = await res.json();
        
        thinkingDiv.classList.remove('searching-bubble');
        thinkingDiv.innerHTML = `<div class="bubble">${data.reply}</div>`;
        speak(data.reply);
    } catch (e) { thinkingDiv.innerText = "Error: Check your connection."; }
};

function renderMessage(text, role) {
    const d = document.createElement('div');
    d.className = `message ${role}`;
    d.innerHTML = `<div class="bubble">${text}</div>`;
    chatWindow.appendChild(d);
    chatWindow.scrollTop = chatWindow.scrollHeight;
}
